const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Guide',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guide',
        },
      ],
    },
  ],
  api: [
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
};

module.exports = sidebars;
